# Generated by Django 3.0.7 on 2020-06-25 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='post',
            name='mail',
        ),
    ]
